package com.example.chen1.uncom.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.chen1.uncom.bean.MessageHistoryBean;
import com.example.chen1.uncom.bean.NewRelationShipBean;
import com.example.chen1.uncom.bean.RelationShipLevelBean;
import com.example.chen1.uncom.bean.RoutineBean;
import com.example.chen1.uncom.bean.UserBean;

import com.example.chen1.uncom.bean.MessageHistoryBeanDao;
import com.example.chen1.uncom.bean.NewRelationShipBeanDao;
import com.example.chen1.uncom.bean.RelationShipLevelBeanDao;
import com.example.chen1.uncom.bean.RoutineBeanDao;
import com.example.chen1.uncom.bean.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageHistoryBeanDaoConfig;
    private final DaoConfig newRelationShipBeanDaoConfig;
    private final DaoConfig relationShipLevelBeanDaoConfig;
    private final DaoConfig routineBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final MessageHistoryBeanDao messageHistoryBeanDao;
    private final NewRelationShipBeanDao newRelationShipBeanDao;
    private final RelationShipLevelBeanDao relationShipLevelBeanDao;
    private final RoutineBeanDao routineBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageHistoryBeanDaoConfig = daoConfigMap.get(MessageHistoryBeanDao.class).clone();
        messageHistoryBeanDaoConfig.initIdentityScope(type);

        newRelationShipBeanDaoConfig = daoConfigMap.get(NewRelationShipBeanDao.class).clone();
        newRelationShipBeanDaoConfig.initIdentityScope(type);

        relationShipLevelBeanDaoConfig = daoConfigMap.get(RelationShipLevelBeanDao.class).clone();
        relationShipLevelBeanDaoConfig.initIdentityScope(type);

        routineBeanDaoConfig = daoConfigMap.get(RoutineBeanDao.class).clone();
        routineBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        messageHistoryBeanDao = new MessageHistoryBeanDao(messageHistoryBeanDaoConfig, this);
        newRelationShipBeanDao = new NewRelationShipBeanDao(newRelationShipBeanDaoConfig, this);
        relationShipLevelBeanDao = new RelationShipLevelBeanDao(relationShipLevelBeanDaoConfig, this);
        routineBeanDao = new RoutineBeanDao(routineBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(MessageHistoryBean.class, messageHistoryBeanDao);
        registerDao(NewRelationShipBean.class, newRelationShipBeanDao);
        registerDao(RelationShipLevelBean.class, relationShipLevelBeanDao);
        registerDao(RoutineBean.class, routineBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        messageHistoryBeanDaoConfig.clearIdentityScope();
        newRelationShipBeanDaoConfig.clearIdentityScope();
        relationShipLevelBeanDaoConfig.clearIdentityScope();
        routineBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public MessageHistoryBeanDao getMessageHistoryBeanDao() {
        return messageHistoryBeanDao;
    }

    public NewRelationShipBeanDao getNewRelationShipBeanDao() {
        return newRelationShipBeanDao;
    }

    public RelationShipLevelBeanDao getRelationShipLevelBeanDao() {
        return relationShipLevelBeanDao;
    }

    public RoutineBeanDao getRoutineBeanDao() {
        return routineBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
