package com.example.chen1.uncom.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.chen1.uncom.bean.RelationShipLevelBean;
import com.example.chen1.uncom.bean.UserBean;
import com.example.chen1.uncom.bean.MessageHistoryBean;

import com.example.chen1.uncom.bean.RelationShipLevelBeanDao;
import com.example.chen1.uncom.bean.UserBeanDao;
import com.example.chen1.uncom.bean.MessageHistoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig relationShipLevelBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig messageHistoryBeanDaoConfig;

    private final RelationShipLevelBeanDao relationShipLevelBeanDao;
    private final UserBeanDao userBeanDao;
    private final MessageHistoryBeanDao messageHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        relationShipLevelBeanDaoConfig = daoConfigMap.get(RelationShipLevelBeanDao.class).clone();
        relationShipLevelBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        messageHistoryBeanDaoConfig = daoConfigMap.get(MessageHistoryBeanDao.class).clone();
        messageHistoryBeanDaoConfig.initIdentityScope(type);

        relationShipLevelBeanDao = new RelationShipLevelBeanDao(relationShipLevelBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        messageHistoryBeanDao = new MessageHistoryBeanDao(messageHistoryBeanDaoConfig, this);

        registerDao(RelationShipLevelBean.class, relationShipLevelBeanDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(MessageHistoryBean.class, messageHistoryBeanDao);
    }
    
    public void clear() {
        relationShipLevelBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        messageHistoryBeanDaoConfig.clearIdentityScope();
    }

    public RelationShipLevelBeanDao getRelationShipLevelBeanDao() {
        return relationShipLevelBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public MessageHistoryBeanDao getMessageHistoryBeanDao() {
        return messageHistoryBeanDao;
    }

}
