/*
var loadDateModel={
	tartgetUrl:"",
	page:1,
	getDate:function(){
		console.log("showDate")
	},
	showDate:function(){
		console.log("showDate")
	},
	start:function(){
		this.getDate()
		this.showDate()
	}
}*/
function loadDataModel(){
	this.targetUrl=""
	this.page=1
	this.getDate=function(){
		console.log("showDate")
	}
	this.showDate=function(){
		console.log("showDate")
	}
	this.start=function(){
		this.getDate()
		this.showDate()
	}
}
